contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #pplaceeval channel"
    url: https://nfcore.slack.com/channels/pplaceeval
    about: Discussion about the nf-core/pplaceeval pipeline
