# You can use this file to create a conda environment for the R modules in this pipeline:
#   conda env create -f environment.yml
name: pplaceeval-r
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - bioconductor-ggtree=3.6.0
    - bioconductor-biostrings=2.66.0
    - r-tidyverse=1.3.1
    - r-ape=5.7
